// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ApplyAutoSaver(arg1:string,arg2:string):Promise<void>;

export function ApplyPacketFilter(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckPacket(arg1:app.PacketInfo):Promise<boolean>;

export function GetTotalPacketCountStr():Promise<string>;

export function RefreshAvailableInterfaces():Promise<void>;

export function ResetTotalPacketCount():Promise<void>;

export function SavePacket(arg1:app.PacketInfo):Promise<void>;

export function SelectInterface(arg1:number):Promise<void>;

export function StartPacketSniffing(arg1:number):Promise<void>;

export function StopPacketSniffing():Promise<void>;
