// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAutoSaver(arg1, arg2) {
  return window['go']['app']['App']['ApplyAutoSaver'](arg1, arg2);
}

export function ApplyPacketFilter(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyPacketFilter'](arg1, arg2, arg3);
}

export function CheckPacket(arg1) {
  return window['go']['app']['App']['CheckPacket'](arg1);
}

export function GetTotalPacketCountStr() {
  return window['go']['app']['App']['GetTotalPacketCountStr']();
}

export function RefreshAvailableInterfaces() {
  return window['go']['app']['App']['RefreshAvailableInterfaces']();
}

export function ResetTotalPacketCount() {
  return window['go']['app']['App']['ResetTotalPacketCount']();
}

export function SavePacket(arg1) {
  return window['go']['app']['App']['SavePacket'](arg1);
}

export function SelectInterface(arg1) {
  return window['go']['app']['App']['SelectInterface'](arg1);
}

export function StartPacketSniffing(arg1) {
  return window['go']['app']['App']['StartPacketSniffing'](arg1);
}

export function StopPacketSniffing() {
  return window['go']['app']['App']['StopPacketSniffing']();
}
